### ISSUE TITLE
Jugador Fácil y Difícil

### ISSUE THREAD

**Issue by cerillo2808** [cerillo2808/4_en_linea#25]
Sólo tiran en la primera columna, y se enciclan cuando está lleno.

**Comment by MelanyAlfaro** [comment]
con las IAs aun no se puede jugar, porque el método jugar, no devuelve una columna

**Comment by cerillo2808** [comment]
ya estado tiene un metodo para hacer jugar a las ias que devuelve la columna. Falta usarlo en la GUI
